services:
  blacklist-postgres:
    image: blacklist-postgres:ci

  blacklist-redis:
    image: blacklist-redis:ci

  blacklist-collector:
    image: blacklist-collector:ci

  blacklist-app:
    image: blacklist-app:ci
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: blacklist-dev-password

  blacklist-frontend:
    image: blacklist-frontend:ci
    ports: !override
      - "3443:3000"
