services:
  blacklist-postgres:
    extends:
      file: base.yml
      service: blacklist-postgres
    image: blacklist-postgres:latest

  blacklist-redis:
    extends:
      file: base.yml
      service: blacklist-redis
    image: blacklist-redis:latest

  blacklist-collector:
    extends:
      file: base.yml
      service: blacklist-collector
    image: blacklist-collector:latest

  blacklist-app:
    extends:
      file: base.yml
      service: blacklist-app
    image: blacklist-app:latest

  blacklist-frontend:
    extends:
      file: base.yml
      service: blacklist-frontend
    image: blacklist-frontend:latest
    volumes:
      - ./ssl:/app/ssl:ro

volumes:
  blacklist-pgdata:
  blacklist-redis-data:
  blacklist-collector-data:
  blacklist-logs:
  blacklist-uploads:
  blacklist-app-data:
